export const SENSORY_MODES = {
  default: {
    colors: {
      primary: '#4A90D9',
      secondary: '#7B61FF',
      background: '#FFFFFF',
      surface: '#F5F5F5',
      text: '#1A1A1A',
      success: '#34C759',
      warning: '#FF9500',
      error: '#FF3B30',
    },
    animation: { enabled: true, duration: 300 },
    haptic: { enabled: true, intensity: 'medium' as const },
    sound: { enabled: true, volume: 0.7 },
    borderRadius: 12,
    spacing: { base: 8 },
  },
  low_stimulation: {
    colors: {
      primary: '#6B7B8D',
      secondary: '#8E99A4',
      background: '#F0EDE8',
      surface: '#E8E4DF',
      text: '#3D3D3D',
      success: '#6B8E6B',
      warning: '#B8956B',
      error: '#B87070',
    },
    animation: { enabled: false, duration: 0 },
    haptic: { enabled: false, intensity: 'none' as const },
    sound: { enabled: false, volume: 0 },
    borderRadius: 8,
    spacing: { base: 12 },
  },
  high_contrast: {
    colors: {
      primary: '#0000FF',
      secondary: '#FF00FF',
      background: '#000000',
      surface: '#1A1A1A',
      text: '#FFFFFF',
      success: '#00FF00',
      warning: '#FFFF00',
      error: '#FF0000',
    },
    animation: { enabled: false, duration: 0 },
    haptic: { enabled: true, intensity: 'strong' as const },
    sound: { enabled: true, volume: 1.0 },
    borderRadius: 0,
    spacing: { base: 10 },
  },
} as const;
